name: Validate
on: [push, pull_request]

jobs:
  build-jekyll:
    name: Build Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Jekyll site
      uses: jerryjvl/jekyll-build-action@v1

  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Lint markdown
      uses: avto-dev/markdown-lint@v1
      with:
        args: '**/*.md'
        config: '.github/workflows/config/markdown-lint_config.yml'

  broken-links:
    name: Check for broken links
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@0.40.0
      with:
        config_path: .github/workflows/config/spellcheck.yml
